Repository gopalthedev/youtube, pull requests merged in 2023-10, with the labels that each got.

#5 Revert "Update subscriptions.dart"
  lib/subscriptions.dart
Labels: hactoberfest, hatoberfest-accepted

#7 Update subscriptions.dart
  lib/subscriptions.dart
Labels: hactoberfest, hactoberfest-accepted

#9 Update explore.dart
  lib/explore.dart
Labels: hacktoberfest, hacktoberfest-accepted
